In [19]:
import pandas as pd
import numpy as np

np.random.seed(0)

random_text = ['hi','hello','bye','bye bye']
sentiment = np.random.choice(random_text,size=(60,))

data = {
    'sentiment': sentiment,
    'mood': ['good' if s == 'hello' else
             'bad' for s in sentiment]
}

data = pd.DataFrame(data)
data.to_csv('mymood.csv',index=False)

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense
# for text Transoformation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
# for lable encoding
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
# for train test split
from sklearn.model_selection import train_test_split

In [26]:
print(data.head())

  sentiment  mood
0        hi   bad
1   bye bye   bad
2     hello  good
3        hi   bad
4   bye bye   bad


In [29]:
x = data['sentiment']
y = data['mood']
print(x.head())
print(y.head())

0         hi
1    bye bye
2      hello
3         hi
4    bye bye
Name: sentiment, dtype: object
0     bad
1     bad
2    good
3     bad
4     bad
Name: mood, dtype: object


In [34]:
# transforming x
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)
x_token = tokenizer.texts_to_sequences(x)

main_x = pad_sequences(x_token,maxlen=3)
# print(main_x)

In [36]:
# now transofrming y

labelenco = LabelEncoder()
y_tran = labelenco.fit_transform(y)

main_y = to_categorical(y_tran,num_classes=2)

In [37]:
print(main_x)
print(main_y)

[[0 0 2]
 [0 1 1]
 [0 0 3]
 [0 0 2]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 0 3]
 [0 1 1]
 [0 0 3]
 [0 0 1]
 [0 0 2]
 [0 1 1]
 [0 0 1]
 [0 0 2]
 [0 0 2]
 [0 0 2]
 [0 0 1]
 [0 0 3]
 [0 0 1]
 [0 1 1]
 [0 1 1]
 [0 0 1]
 [0 0 2]
 [0 0 3]
 [0 0 3]
 [0 0 3]
 [0 0 3]
 [0 0 2]
 [0 0 3]
 [0 0 2]
 [0 1 1]
 [0 0 2]
 [0 1 1]
 [0 0 3]
 [0 0 1]
 [0 1 1]
 [0 1 1]
 [0 0 2]
 [0 0 1]
 [0 1 1]
 [0 0 2]
 [0 0 3]
 [0 1 1]
 [0 0 3]
 [0 1 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [0 0 2]
 [0 0 3]
 [0 0 3]
 [0 0 3]
 [0 1 1]
 [0 0 2]
 [0 1 1]
 [0 0 1]
 [0 0 2]
 [0 1 1]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]


In [39]:
x_train, x_test, y_train, y_test = train_test_split(main_x,main_y,test_size=0.3,random_state=30)

In [40]:
print('x_trainshape: ',x_train.shape)
print('x_testshape: ',x_test.shape)
print('y_trainshape: ',y_train.shape)
print('y_testshape: ',y_test.shape)

x_trainshape:  (42, 3)
x_testshape:  (18, 3)
y_trainshape:  (42, 2)
y_testshape:  (18, 2)


In [42]:
GRU_model = Sequential ([
    GRU(units=64,activation='relu',input_shape=(3,1)),
    Dense(2,activation="softmax")
])

C:\Users\naman\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [43]:
GRU_model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [44]:
GRU_model.fit(x_train,y_train,epochs=10,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 411ms/step - accuracy: 0.2788 - loss: 0.6938 - val_accuracy: 0.2222 - val_loss: 0.6947
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.2579 - loss: 0.6933 - val_accuracy: 0.2222 - val_loss: 0.6936
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.2684 - loss: 0.6921 - val_accuracy: 0.2222 - val_loss: 0.6923
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.3373 - loss: 0.6912 - val_accuracy: 0.7222 - val_loss: 0.6912
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7579 - loss: 0.6902 - val_accuracy: 0.7222 - val_loss: 0.6901
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8100 - loss: 0.6887 - val_accuracy: 0.7222 - val_loss: 0.6887
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7579 - loss: 0.6882 - val_accuracy: 0.7222 - val_loss: 0.6879
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7897 - loss: 0.6874 - val_accuracy: 1.0000 - val_loss: 0.6868

In [45]:
loss, accuracy = GRU_model.evaluate(x_test,y_test)
print("Model Accuracy: ", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.6847
Model Accuracy:  1.0
