In [2]:
# data Set making for LSTM

#movie review sentiment analysis
import pandas as pd
import numpy as np

np.random.seed(0)

review_text = ['bhaut achi he movie','thik he','bekar the movie']

review = np.random.choice(review_text,size=(50,))

In [4]:
data = {
    'review_text': review,
    'sentiment': ['positive' if s == 'bhaut achi he movie' else
                  'neutral' if s == 'thik he' else
                  'negative' for s in review]
}

data = pd.DataFrame(data)
data.to_csv('movie_review_sen.csv',index=False)

In [5]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
# for sentence encoding
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
# for lables encoding
from sklearn.preprocessing import LabelEncoder

In [6]:
data.head()

review_text sentiment
0  bhaut achi he movie  positive
1              thik he   neutral
2  bhaut achi he movie  positive
3              thik he   neutral
4              thik he   neutral

In [7]:
x = data['review_text']
y = data['sentiment']
print(x.head())
print(y.head())

0    bhaut achi he movie
1                thik he
2    bhaut achi he movie
3                thik he
4                thik he
Name: review_text, dtype: object
0    positive
1     neutral
2    positive
3     neutral
4     neutral
Name: sentiment, dtype: object


In [8]:
# x transofrmation text to encoding using tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)
x_tran = tokenizer.texts_to_sequences(x)
print(x_tran)

[[3, 4, 1, 2], [5, 1], [3, 4, 1, 2], [5, 1], [5, 1], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [3, 4, 1, 2], [3, 4, 1, 2], [6, 7, 2], [5, 1], [6, 7, 2], [6, 7, 2], [3, 4, 1, 2], [5, 1], [5, 1], [5, 1], [5, 1], [3, 4, 1, 2], [5, 1], [3, 4, 1, 2], [3, 4, 1, 2], [5, 1], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [5, 1], [5, 1], [6, 7, 2], [3, 4, 1, 2], [5, 1], [5, 1], [5, 1], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [3, 4, 1, 2], [3, 4, 1, 2], [5, 1], [5, 1], [6, 7, 2], [3, 4, 1, 2]]


In [9]:
x_padded = pad_sequences(x_tran, maxlen=5)

In [10]:
print(x_padded)

[[0 3 4 1 2]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]]


In [11]:
labelenco = LabelEncoder()
y_tran = labelenco.fit_transform(y)
print(y_tran)

from keras.utils import to_categorical

num_classes = 3  # Assuming you have 3 classes (positive, neutral, negative)

# Convert target labels to one-hot encoded format
y_one_hot = to_categorical(y_tran, num_classes=num_classes)
print(y_one_hot)

[2 1 2 1 1 0 2 0 2 2 2 0 1 0 0 2 1 1 1 1 2 1 2 2 1 0 2 0 2 1 1 0 2 1 1 1 2
 0 2 0 0 2 0 2 2 2 1 1 0 2]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [12]:
x_train,x_test,y_train,y_test = train_test_split(x_padded,y_one_hot,test_size=0.30,random_state=35)

In [13]:
print("x_trainshape:",x_train.shape)
print("x_testshape:",x_test.shape)
print("y_trainshape:",y_train.shape)
print("y_testshape:",y_test.shape)

x_trainshape: (35, 5)
x_testshape: (15, 5)
y_trainshape: (35, 3)
y_testshape: (15, 3)


In [16]:
from tensorflow.keras.layers import LSTM
LSTM_model = Sequential([
    LSTM(units=64,activation='relu',input_shape=(5,1)),
    Dense(3,activation='softmax')
])

In [17]:
LSTM_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [18]:
LSTM_model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - accuracy: 0.2548 - loss: 1.0856 - val_accuracy: 0.2667 - val_loss: 1.0721
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2652 - loss: 1.0729 - val_accuracy: 0.2667 - val_loss: 1.0632
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.2652 - loss: 1.0635 - val_accuracy: 0.2667 - val_loss: 1.0576
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.2548 - loss: 1.0603 - val_accuracy: 0.2667 - val_loss: 1.0523
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.2652 - loss: 1.0524 - val_accuracy: 0.2667 - val_loss: 1.0469
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2443 - loss: 1.0514 - val_accuracy: 0.2667 - val_loss: 1.0418
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.2443 - loss: 1.0468 - val_accuracy: 0.2667 - val_loss: 1.0358
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.2548 - loss: 1.0388 - val_accuracy: 0.2667 - val_loss: 1.0293

In [21]:
loss, accuracy = LSTM_model.evaluate(x_test,y_test)
print(loss)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.2667 - loss: 1.0165
1.0165351629257202
0.2666666805744171


In [23]:
y_pred = LSTM_model.predict(x_test)
print(y_pred)
print(y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step
[[0.46199536 0.2107546  0.32724994]
 [0.38315693 0.26141453 0.35542846]
 [0.38315693 0.26141453 0.35542846]
 [0.46199536 0.2107546  0.32724994]
 [0.3600836  0.3040607  0.3358557 ]
 [0.38315693 0.26141453 0.35542846]
 [0.38315693 0.26141453 0.35542846]
 [0.3600836  0.3040607  0.3358557 ]
 [0.46199536 0.2107546  0.32724994]
 [0.38315693 0.26141453 0.35542846]
 [0.3600836  0.3040607  0.3358557 ]
 [0.3600836  0.3040607  0.3358557 ]
 [0.3600836  0.3040607  0.3358557 ]
 [0.38315693 0.26141453 0.35542846]
 [0.46199536 0.2107546  0.32724994]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
