In [170]:
# data Set making for RNN 

#movie review sentiment analysis
import pandas as pd
import numpy as np

np.random.seed(0)

review_text = ['bhaut achi he movie','thik he','bekar the movie']

review = np.random.choice(review_text,size=(50,))

In [171]:
data = {
    'review_text': review,
    'sentiment': ['positive' if s == 'bhaut achi he movie' else
                  'neutral' if s == 'thik he' else
                  'negative' for s in review]
}

data = pd.DataFrame(data)
data.to_csv('movie_review_sen.csv',index=False)

In [172]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# for sentence encoding
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
# for lables encoding
from sklearn.preprocessing import LabelEncoder

In [173]:
data.head()

review_text sentiment
0  bhaut achi he movie  positive
1              thik he   neutral
2  bhaut achi he movie  positive
3              thik he   neutral
4              thik he   neutral

In [174]:
x = data['review_text']
y = data['sentiment']
print(x.head())
print(y.head())

0    bhaut achi he movie
1                thik he
2    bhaut achi he movie
3                thik he
4                thik he
Name: review_text, dtype: object
0    positive
1     neutral
2    positive
3     neutral
4     neutral
Name: sentiment, dtype: object


In [175]:
# x transofrmation text to encoding using tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)
x_tran = tokenizer.texts_to_sequences(x)
print(x_tran)

[[3, 4, 1, 2], [5, 1], [3, 4, 1, 2], [5, 1], [5, 1], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [3, 4, 1, 2], [3, 4, 1, 2], [6, 7, 2], [5, 1], [6, 7, 2], [6, 7, 2], [3, 4, 1, 2], [5, 1], [5, 1], [5, 1], [5, 1], [3, 4, 1, 2], [5, 1], [3, 4, 1, 2], [3, 4, 1, 2], [5, 1], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [5, 1], [5, 1], [6, 7, 2], [3, 4, 1, 2], [5, 1], [5, 1], [5, 1], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [6, 7, 2], [3, 4, 1, 2], [6, 7, 2], [3, 4, 1, 2], [3, 4, 1, 2], [3, 4, 1, 2], [5, 1], [5, 1], [6, 7, 2], [3, 4, 1, 2]]


In [176]:
x_padded = pad_sequences(x_tran, maxlen=5)

In [177]:
print(x_padded)

[[0 3 4 1 2]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 0 6 7 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 3 4 1 2]
 [0 0 0 5 1]
 [0 0 0 5 1]
 [0 0 6 7 2]
 [0 3 4 1 2]]


In [178]:
labelenco = LabelEncoder()
y_tran = labelenco.fit_transform(y)
print(y_tran)

from keras.utils import to_categorical

num_classes = 3  # Assuming you have 3 classes (positive, neutral, negative)

# Convert target labels to one-hot encoded format
y_one_hot = to_categorical(y_tran, num_classes=num_classes)
print(y_one_hot)

[2 1 2 1 1 0 2 0 2 2 2 0 1 0 0 2 1 1 1 1 2 1 2 2 1 0 2 0 2 1 1 0 2 1 1 1 2
 0 2 0 0 2 0 2 2 2 1 1 0 2]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [179]:
x_train,x_test,y_train,y_test = train_test_split(x_padded,y_one_hot,test_size=0.30,random_state=35)

In [180]:
print("x_trainshape:",x_train.shape)
print("x_testshape:",x_test.shape)
print("y_trainshape:",y_train.shape)
print("y_testshape:",y_test.shape)

x_trainshape: (35, 5)
x_testshape: (15, 5)
y_trainshape: (35, 3)
y_testshape: (15, 3)


In [181]:
from tensorflow.keras.layers import SimpleRNN
RNN_model = Sequential([
    SimpleRNN(units=64,activation='relu',input_shape=(5,1)),
    Dense(3,activation='softmax')
])

C:\Users\naman\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [182]:
RNN_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [183]:
RNN_model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 230ms/step - accuracy: 0.3536 - loss: 1.0502 - val_accuracy: 0.3333 - val_loss: 0.9981
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.3432 - loss: 0.9923 - val_accuracy: 0.6000 - val_loss: 0.9440
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5875 - loss: 0.9376 - val_accuracy: 0.6000 - val_loss: 0.9004
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5875 - loss: 0.9006 - val_accuracy: 0.6000 - val_loss: 0.8633
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5979 - loss: 0.8639 - val_accuracy: 0.6000 - val_loss: 0.8262
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5979 - loss: 0.8266 - val_accuracy: 0.6000 - val_loss: 0.7895
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5875 - loss: 0.7952 - val_accuracy: 0.6000 - val_loss: 0.7513
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5979 - loss: 0.7510 - val_accuracy: 0.6000 - val_loss: 0.7104

In [184]:
loss, accuracy = RNN_model.evaluate(x_test,y_test)
print(loss)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.6210
0.6210209131240845
1.0


In [169]:
y_pred = RNN_model.predict(x_test)
print(y_pred)
print(y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[0.79554003 0.12018701 0.08427294]
 [0.10281778 0.10056185 0.7966204 ]
 [0.10281778 0.10056185 0.7966204 ]
 [0.79554003 0.12018701 0.08427294]
 [0.18739428 0.7157131  0.09689264]
 [0.10281778 0.10056185 0.7966204 ]
 [0.10281778 0.10056185 0.7966204 ]
 [0.18739428 0.7157131  0.09689264]
 [0.79554003 0.12018701 0.08427294]
 [0.10281778 0.10056185 0.7966204 ]
 [0.18739428 0.7157131  0.09689264]
 [0.18739428 0.7157131  0.09689264]
 [0.18739428 0.7157131  0.09689262]
 [0.10281778 0.10056185 0.7966204 ]
 [0.79554015 0.12018704 0.08427289]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
