# TensorFlow Basics

In [1]:
import tensorflow as tf

## Arithmetic Operations

In [2]:
a = tf.constant(3)
b = tf.constant(4)

c = tf.add(a,b)
print("sum of node a and b is ", c)

sum of node a and b is  tf.Tensor(7, shape=(), dtype=int32)


In [3]:
import tensorflow as tf

# Define two tensors
a = tf.constant(3)
b = tf.constant(4)

# Addition
c = tf.add(a, b)
print("Addition result:", c.numpy())  # .numpy() converts the tensor to a NumPy array


Addition result: 7


## Matrix Operations

In [4]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
result = tf.matmul(matrix_a, matrix_b)
print("Matrix multiplication result:")
print(result.numpy())


Matrix multiplication result:
[[19 22]
 [43 50]]


## Mathematical Functions

In [5]:
import tensorflow as tf

# Define a tensor
tensor = tf.constant([1.0, 2.0, 3.0])

# Square root
sqrt_tensor = tf.sqrt(tensor)
print("Square root:")
print(sqrt_tensor.numpy())


Square root:
[1.        1.4142135 1.7320508]


## Reduction Operations

In [6]:
import tensorflow as tf

# Define a tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Summation
sum_tensor = tf.reduce_sum(tensor)
print("Summation result:", sum_tensor.numpy())


Summation result: 10


## Comparisons and Logical Operations

In [7]:
import tensorflow as tf

# Define two tensors
a = tf.constant([1, 2, 3])
b = tf.constant([2, 2, 2])

# Greater than comparison
greater_than = tf.greater(a, b)
print("Greater than comparison result:")
print(greater_than.numpy())


Greater than comparison result:
[False False  True]


## other Usefull Stuf

In [9]:
import tensorflow as tf

# Reshaping
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
reshaped_tensor = tf.reshape(tensor, [2, 3])
print("Normal tensor:")
print(tensor.numpy())

print("Reshaped tensor:")
print(reshaped_tensor.numpy())


Normal tensor:
[[1 2]
 [3 4]
 [5 6]]
Reshaped tensor:
[[1 2 3]
 [4 5 6]]


In [12]:
# for defining variables is node
variable = tf.Variable([[1,0],[0,1]])
print(variable.numpy())

[[1 0]
 [0 1]]
